import { browser } from 'k6/experimental/browser';
import { LoginPage } from "../pages/login-page.js";

export default function () {
    Login()
}

export async function Login() {
    const context = browser.context();
    const page = context.newPage();

    await page.goto('https://test.k6.io/my_messages.php');

    const loginpage = new LoginPage(page)

    await loginpage.goto();
    await loginpage.submitForm();
}

export function ThinkTime() {
    sleep(randomIntBetween(3, 5));
}

export function setup() {
    // Initialize test, setup data, etc.
}

export function teardown() {
    // Delete data generated by test, etc.
}